# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mine in Abyss
description: >- # this means to ignore newlines until "baseurl:"
  Mine in Abyss is a recreation of Made in Abyss in Minecraft.
  We currently run build and survival servers at build.mineinabyss.ga
  and survive.mineinabyss.ga respectively.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

highlighter: rouge
pygmentsTheme: 'default'

nav:
  Home: '/'
  Tags: '/tags.html'
  Timeline: '/timeline.html'
# Build settings
markdown: kramdown
kramdown:
  input: GFM
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)

paginate: 5
paginate_path: "/page:num/"